### ISSUE TITLE
Exception when appending to XML

### ISSUE THREAD

**Issue by StephanPreibisch** [bigdataviewer/bigdataviewer-core#10]
Hi @tpietzsch,

I was doing a second appending run (maybe related?) and also having the BDV open at the same time and it crashed with this exception:

Exception in thread "Thread-11" ncsa.hdf.hdf5lib.exceptions.HDF5FileInterfaceException: File accessibilty:Unable to open file ["H5Fint.c line 1026 in H5F_open(): file is already open for read-only"]
	at ch.systemsx.cisd.hdf5.hdf5lib.H5.H5Fopen(Native Method)
	at ch.systemsx.cisd.hdf5.hdf5lib.H5F.H5Fopen(H5F.java:50)
	at ch.systemsx.cisd.hdf5.HDF5.openFileReadWrite(HDF5.java:203)
	at ch.systemsx.cisd.hdf5.HDF5BaseWriter.openFile(HDF5BaseWriter.java:215)
	at ch.systemsx.cisd.hdf5.HDF5BaseReader.<init>(HDF5BaseReader.java:141)
	at ch.systemsx.cisd.hdf5.HDF5BaseWriter.<init>(HDF5BaseWriter.java:147)
	at ch.systemsx.cisd.hdf5.HDF5WriterConfigurator.writer(HDF5WriterConfigurator.java:133)
	at ch.systemsx.cisd.hdf5.HDF5FactoryProvider$HDF5Factory.open(HDF5FactoryProvider.java:48)
	at ch.systemsx.cisd.hdf5.HDF5Factory.open(HDF5Factory.java:38)
	at bdv.export.Hdf5BlockWriterThread.<init>(Hdf5BlockWriterThread.java:35)
	at bdv.export.Hdf5BlockWriterThread.<init>(Hdf5BlockWriterThread.java:54)
	at bdv.export.WriteSequenceToHdf5.writeViewToHdf5PartitionFile(WriteSequenceToHdf5.java:465)
	at spim.process.fusion.export.AppendSpimData2HDF5.exportImage(AppendSpimData2HDF5.java:168)
	at spim.process.fusion.export.AppendSpimData2.exportImage(AppendSpimData2.java:58)
	at spim.process.fusion.deconvolution.EfficientBayesianBased.fuseData(EfficientBayesianBased.java:260)
	at spim.fiji.plugin.Image_Fusion.fuse(Image_Fusion.java:173)
	at spim.fiji.plugin.Image_Fusion.fuse(Image_Fusion.java:88)
	at spim.fiji.spimdata.explorer.popup.FusionPopup$MyActionListener$1.run(FusionPopup.java:57)
	at java.lang.Thread.run(Thread.java:662)

I hope this makes sense for you, hopefully just a small hiccup :)

Thanks a lot and cheers,
Stephan

**Comment by StephanPreibisch** [comment]
It actually wrote the first two timepoints with no problem and just crashed on the third one while I was not even at the computer ...

**Comment by tpietzsch** [comment]
@StephanPreibisch No idea what's going on. How many timepoints were you writing. Was the third timepoint the last one? Did this work before or is it reproducible?

**Comment by StephanPreibisch** [comment]
I was writing 40 timepoints, crashed on 3/40. The first deconvolution run of 40 timepoints went fine. I did not have time to try to reproduce it - I thought maybe it tells you something right away. I will try later!
