### ISSUE TITLE
Error message when closing Bdv with active TransformedBoxEditor

### ISSUE THREAD

**Issue by tischi** [bigdataviewer/bigdataviewer-core#58]
@tpietzsch 
When calling `bdvHandle.close()` on a Bdv that currently shows a `TransformedBoxEditor` I am getting below error:
```
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at bdv.tools.VisibilityAndGroupingDialog$GroupingPanel.update(VisibilityAndGroupingDialog.java:571)
	at bdv.tools.VisibilityAndGroupingDialog$GroupingPanel.visibilityChanged(VisibilityAndGroupingDialog.java:606)
	at bdv.viewer.VisibilityAndGrouping.update(VisibilityAndGrouping.java:375)
	at bdv.viewer.ViewerPanel.removeSource(ViewerPanel.java:370)
	at bdv.tools.boundingbox.TransformedBoxOverlaySource.removeFromViewer(TransformedBoxOverlaySource.java:120)
	at bdv.tools.boundingbox.TransformedBoxEditor.uninstall(TransformedBoxEditor.java:180)
	at bdv.tools.boundingbox.TransformedBoxSelectionDialog$1.componentHidden(TransformedBoxSelectionDialog.java:133)
	at java.awt.AWTEventMulticaster.componentHidden(AWTEventMulticaster.java:190)
	at java.awt.Component.processComponentEvent(Component.java:6368)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Window.processEvent(Window.java:2025)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Am I doing something wrong or is this maybe a bug?

**Comment by tpietzsch** [comment]
Looks like this should have been fixed in #52
Are you maybe not using the most recent bigdataviewer-core version?
Could you try explicitly add
```
<dependency>
  <groupId>sc.fiji</groupId>
  <artifactId>bigdataviewer-core</artifactId>
  <version>7.0.0</version>
</dependency>
```
to your dependencies?

**Comment by tischi** [comment]
Yes, thanks that helps!

However, when using the higher version of `bigdataviewer-core` an incompatibility with older versions of `bigdataviewer-vistools` occurred:

There used to be a method called
`RealARGBColorConverter.Imp1( )` 
which is now not present anymore, but one can use
`RealARGBColorConverter.create( )`
instead.

This is not an issue for me locally, because I can just use the latest versions of both packages. 

However it seems that  Fiji still depends on rather old versions of bigdataviewer packages:

https://github.com/scijava/pom-scijava/blob/pom-scijava-27.0.1/pom.xml#L549

So I am not sure this could cause any issues?

**Comment by tpietzsch** [comment]
I uploaded the newest versions to the Fiji update site, but I should make a PR to pom-scijava to bump the versions there. Thanks for the reminder...

**Comment by tpietzsch** [comment]
> I should make a PR to pom-scijava to bump the versions there

Of course, @ctrueden already took care of it! (Thank you so much!)
It's just not released yet.

**Comment by ctrueden** [comment]
Sorry for the slowness in release. I still need to get imagej-ops reconciled with imagej-scripting, and then I can finally release the new pom-scijava 28. My hard deadline is end-of-day Wednesday, since I have a vacation coming up for the next couple of weeks afterward. Will do my best! 🤞

**Comment by tischi** [comment]
Enjoy your holidays! You deserve it!!!!!!
