### ISSUE TITLE
negative display range error

### ISSUE THREAD

**Issue by bogovicj** [bigdataviewer/bigdataviewer-core#62]
To reproduce:
1) Open an image with negative values in fiji.
2) Set the lower bound of brightness/contrast to a negative number
3) open the image with bdv

You'll see
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: invalid range properties
	at javax.swing.DefaultBoundedRangeModel.<init>(DefaultBoundedRangeModel.java:102)
	at javax.swing.JSlider.<init>(JSlider.java:274)
	at bdv.tools.brightness.SliderPanelDouble.<init>(SliderPanelDouble.java:99)
	at bdv.tools.brightness.BrightnessDialog$MinMaxPanel.<init>(BrightnessDialog.java:356)
	at bdv.tools.brightness.BrightnessDialog$MinMaxPanels.recreateContent(BrightnessDialog.java:285)
	at bdv.tools.brightness.BrightnessDialog$2.lambda$update$0(BrightnessDialog.java:120)
	at bdv.util.InvokeOnEDT.invokeAndWait(InvokeOnEDT.java:41)
	at bdv.tools.brightness.BrightnessDialog$2.update(BrightnessDialog.java:118)
	at bdv.tools.brightness.SetupAssignments.removeSetupFromGroup(SetupAssignments.java:176)
	at bdv.tools.brightness.BrightnessDialog$MinMaxPanel$1.actionPerformed(BrightnessDialog.java:385)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
...
```

I can look into this, but not soon :-/ (just don't want to forget)

**Comment by bogovicj** [comment]
Can't seem to reproduce - may have been using an older bigdataviewer.  My fault.  Closing
