### ISSUE TITLE
BDV-N5 cannot load n5 datasets with missing chunks

### ISSUE THREAD

**Issue by constantinpape** [bigdataviewer/bigdataviewer-core#74]
When trying to open an n5 dataset with missing chunks, bigdataviewer fails with the following
exception:
```
Caused by: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:112)
        at net.imglib2.cache.util.LoaderCacheKeyAdapter.get(LoaderCacheKeyAdapter.java:20)
        at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:43)
        at net.imglib2.cache.ref.WeakRefVolatileCache.getBlocking(WeakRefVolatileCache.java:451)
        at net.imglib2.cache.ref.WeakRefVolatileCache.access$000(WeakRefVolatileCache.java:20)
        at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:498)
        at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:475)
        at net.imglib2.cache.queue.FetcherThreads$Fetcher.run(FetcherThreads.java:177)
```

I guess there should be a check in the  [N5 image loader](https://github.com/bigdataviewer/bigdataviewer-core/blob/5d2a1b1ef29d6a321fe6719a49d50fe7e42e2d27/src/main/java/bdv/img/n5/N5ImageLoader.java) that returns a zero-filled array in case of missing chunks.

This is fairly critical for the application we are working on, so any advise on the best way to fix this is highly appreciated :).

cc @tischer

**Comment by tpietzsch** [comment]
@constantinpape Can you provide a small example n5 dataset with missing chunks. I'll try to fix it.

Is it a concern whether the missing chunks appear later? In the simple fix, once a chunk was missing, the image loader will not attempt to reload it.

**Comment by constantinpape** [comment]
@tpietzsch
I have uploaded an example file [here](https://oc.embl.de/index.php/s/KekkDJdMIMPhi4A).

I also had a closer look at the code and I think the issue is that `n5.readBlock` returns `null`, which causes `createArray.apply` to throw the exception [here](https://github.com/bigdataviewer/bigdataviewer-core/blob/5d2a1b1ef29d6a321fe6719a49d50fe7e42e2d27/src/main/java/bdv/img/n5/N5ImageLoader.java#L356).

> Is it a concern whether the missing chunks appear later? In the simple fix, once a chunk was missing, the image loader will not attempt to reload it.

For our application this is not a a concern, we assume that the data is static for a given bigdataviewer session, so it's fine if this is cached and then not update.

**Comment by tischi** [comment]
@constantinpape 
For testing purposes, I implemented a quick fix (see below). It works, i.e. there are no more error messages during loading. So, I think we can proceed under the assumption that your python n5 writer produces valid data.
```
                @Override
		public A loadArray( final long[] gridPosition ) throws IOException
		{
			final DataBlock< ? > block = n5.readBlock( pathName, attributes, gridPosition );

			if ( block == null )
			{
				final int[] blockSize = attributes.getBlockSize();
				final int n = blockSize[ 0 ] * blockSize[ 1 ] * blockSize[ 2 ];
				if ( attributes.getDataType().equals( DataType.UINT16 ))
				{
					final ShortArrayDataBlock shortArrayDataBlock = new ShortArrayDataBlock( blockSize, gridPosition, new short[ n ] );
					return createArray.apply( shortArrayDataBlock );
				}
				else if ( attributes.getDataType().equals( DataType.UINT8 ) )
				{
					final ByteArrayDataBlock byteArrayDataBlock = new ByteArrayDataBlock( blockSize, gridPosition, new byte[ n ] );
					return createArray.apply( byteArrayDataBlock );
				}
				else
				{
					return null;
				}
			}
			else
			{
				return createArray.apply( block );
			}
		}
```

**Comment by tischi** [comment]
@constantinpape  Below is the code supporting all cases.
@tpietzsch Should I make a PR or do you want to do this differently?
```
		@Override
		public A loadArray( final long[] gridPosition ) throws IOException
		{
			DataBlock< ? > block = n5.readBlock( pathName, attributes, gridPosition );
			if ( block == null )
			{
				final int[] blockSize = attributes.getBlockSize();
				final int n = blockSize[ 0 ] * blockSize[ 1 ] * blockSize[ 2 ];
				switch ( attributes.getDataType() )
				{
					case UINT8:
					case INT8:
						return createArray.apply( new ByteArrayDataBlock( blockSize, gridPosition, new byte[ n ] ) );
					case UINT16:
					case INT16:
						return createArray.apply( new ShortArrayDataBlock( blockSize, gridPosition, new short[ n ] ) );
					case UINT32:
					case INT32:
						return createArray.apply( new IntArrayDataBlock( blockSize, gridPosition, new int[ n ] ) );
					case UINT64:
					case INT64:
						return createArray.apply( new LongArrayDataBlock( blockSize, gridPosition, new long[ n ] ) );
					case FLOAT32:
						return createArray.apply( new FloatArrayDataBlock( blockSize, gridPosition, new float[ n ] ) );
					case FLOAT64:
						return createArray.apply( new DoubleArrayDataBlock( blockSize, gridPosition, new double[ n ] ) );
					default:
						throw new IllegalArgumentException();
				}
			}
			else
			{
				return createArray.apply( block );
			}
		}
	}
```
