### ISSUE TITLE
NullPointerException thrown if the first view of first timepoint is missing

### ISSUE THREAD

**Issue by StephanPreibisch** [bigdataviewer/bigdataviewer-core#9]
Hi, @tpietzsch,

if the first view of first timepoint is missing, a NPE is thrown. You just need to check in InitializeViewerState if the source interval is null:

final Interval sourceInterval = source.getSpimSource().getSource( timepoint, 0 );

I am not submitting a pull request because I am not sure if you want to look for a view that is present and display that one or simply not do anything. Below is the stack trace.

Cheers,
Stephan

java.lang.NullPointerException
	at bdv.tools.InitializeViewerState.initTransform(InitializeViewerState.java:77)
	at bdv.tools.InitializeViewerState.initTransform(InitializeViewerState.java:44)
	at bdv.BigDataViewer.<init>(BigDataViewer.java:416)
	at spim.fiji.spimdata.explorer.popup.BDVPopup.createBDV(BDVPopup.java:109)
	at spim.fiji.spimdata.explorer.popup.BDVPopup$MyActionListener$1.run(BDVPopup.java:72)
	at java.lang.Thread.run(Thread.java:695)

**Comment by tpietzsch** [comment]
Thanks @StephanPreibisch! I fixed it with "do nothing if source is not present".

Note, that InitializeViewerState uses the current source and the current timepoint, so if you want to do something more clever on the SPIM_Registration side, you can set the current source and timepoint to something that exists and then call InitializeViewerState.initTransform() and/or InitializeViewerState.initBrightness() at any time.

Should I release a new version with this fix?

**Comment by StephanPreibisch** [comment]
Please wait a bit, there is another issue if the HDF5 is appended. BDV does not show the new view right away unless you restart it. But this could be on my side as well ... I am checking this.

**Comment by StephanPreibisch** [comment]
And thanks @tpietzsch :)

**Comment by tpietzsch** [comment]
Hmm, it's not on your side. The BDV is not supposed to show the new view. It does not re-scan the SpimData for new setups. And it shouldn't, the original assumption was the SpimData is immutable, we're bending this assumption already. If you want to do that, you would have to manually add the new source.
Or just close and re-open the BDV window....

**Comment by StephanPreibisch** [comment]
I guess close & open is the way to go for now ...
