### ISSUE TITLE
Minimizing the window height to zero pixel creates an IllegalArgumentException

### ISSUE THREAD

**Issue by NicoKiaru** [bigdataviewer/bigdataviewer-core#96]
It's not a normal situation, but if the window is shrunk to the maximum, then an exception is thrown:

```
Exception in thread "PainterThread" java.lang.IllegalArgumentException: Width (310) and height (0) must be > 0
	at java.awt.image.SampleModel.<init>(SampleModel.java:126)
	at java.awt.image.SinglePixelPackedSampleModel.<init>(SinglePixelPackedSampleModel.java:144)
	at java.awt.image.SinglePixelPackedSampleModel.<init>(SinglePixelPackedSampleModel.java:110)
	at java.awt.image.SinglePixelPackedSampleModel.createCompatibleSampleModel(SinglePixelPackedSampleModel.java:219)
	at net.imglib2.display.screenimage.awt.ARGBScreenImage.<init>(ARGBScreenImage.java:91)
	at bdv.viewer.render.MultiResolutionRenderer.checkResize(MultiResolutionRenderer.java:386)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:462)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:483)
	at net.imglib2.ui.PainterThread.run(PainterThread.java:86)
```

**Comment by tpietzsch** [comment]
This should be resolved by #99 
@NicoKiaru Could you check?

**Comment by NicoKiaru** [comment]
I tested and there's no more exception in `generic-renderer-revised` branch, thanks!

**Comment by NicoKiaru** [comment]
Hum, I found another time this error with the `9.0.6` version:
```
Exception in thread "PainterThread" java.lang.IllegalArgumentException: Width (0) and height (433) must be > 0
	at java.awt.image.SampleModel.<init>(SampleModel.java:126)
	at java.awt.image.SinglePixelPackedSampleModel.<init>(SinglePixelPackedSampleModel.java:144)
	at java.awt.image.SinglePixelPackedSampleModel.<init>(SinglePixelPackedSampleModel.java:110)
	at java.awt.image.SinglePixelPackedSampleModel.createCompatibleSampleModel(SinglePixelPackedSampleModel.java:219)
	at net.imglib2.display.screenimage.awt.ARGBScreenImage.<init>(ARGBScreenImage.java:91)
	at bdv.viewer.render.MultiResolutionRenderer.checkResize(MultiResolutionRenderer.java:385)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:461)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:482)
	at net.imglib2.ui.PainterThread.run(PainterThread.java:86)
```

This time with the width : this happens if you open the cardpanel and shrink the size of the window until only the cardpanel is displayed.

**Comment by NicoKiaru** [comment]
I think this is fixed as well -  I can't reproduce anymore.

**Comment by smith6jt-cop** [comment]
There may be trouble reproducing as this appears to happen at random, but getting this occasionally when scrolling in z direction Big_Stitcher-1.2.14:

Exception in thread "PainterThread" java.lang.NullPointerException
	at net.imglib2.realtransform.AffineTransform3D.updateDs(AffineTransform3D.java:382)
	at net.imglib2.realtransform.AffineTransform3D.<init>(AffineTransform3D.java:340)
	at net.imglib2.realtransform.AffineTransform3D.<init>(AffineTransform3D.java:324)
	at bdv.viewer.render.ProjectorFactory.getTransformedSource(ProjectorFactory.java:291)
	at bdv.viewer.render.ProjectorFactory.createSingleSourceVolatileProjector(ProjectorFactory.java:250)
	at bdv.viewer.render.ProjectorFactory.createSingleSourceProjector(ProjectorFactory.java:205)
	at bdv.viewer.render.ProjectorFactory.createProjector(ProjectorFactory.java:186)
	at bdv.viewer.render.MultiResolutionRenderer.createProjector(MultiResolutionRenderer.java:669)
	at bdv.viewer.render.MultiResolutionRenderer.paintFullFrame(MultiResolutionRenderer.java:478)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:452)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:464)
	at bdv.viewer.render.PainterThread.run(PainterThread.java:87)

**Comment by smith6jt-cop** [comment]
Frequent freezing of BigDataViewer using BigStitcher when scrolling in z-direction.  Intermittent so not sure what is causing it:
[WARNING] 2 exceptions occurred during plugin discovery.
closing
closing
Exception in thread "PainterThread" java.lang.NullPointerException
	at net.imglib2.realtransform.AffineTransform3D.applyInverse(AffineTransform3D.java:468)
	at bdv.viewer.render.Prefetcher.scan(Prefetcher.java:123)
	at bdv.viewer.render.Prefetcher.fetchCells(Prefetcher.java:58)
	at bdv.viewer.render.ProjectorFactory.prefetch(ProjectorFactory.java:331)
	at bdv.viewer.render.ProjectorFactory.createSingleSourceVolatileProjector(ProjectorFactory.java:244)
	at bdv.viewer.render.ProjectorFactory.createSingleSourceProjector(ProjectorFactory.java:205)
	at bdv.viewer.render.ProjectorFactory.createProjector(ProjectorFactory.java:186)
	at bdv.viewer.render.MultiResolutionRenderer.createProjector(MultiResolutionRenderer.java:669)
	at bdv.viewer.render.MultiResolutionRenderer.paintFullFrame(MultiResolutionRenderer.java:478)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:452)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:464)
	at bdv.viewer.render.PainterThread.run(PainterThread.java:87)
closing
[WARNING] 2 exceptions occurred during plugin discovery.
